<?php include("connection.php");SESSION_start();$email=$_SESSION['email'];if($email==""){	header('location:index.php');}error_reporting(0);$email=$_SESSION['email'];$query="SELECT * FROM registeration WHERE email='$email'";$result=mysqli_query($conn,$query);$b=mysqli_fetch_assoc($result);?>
<html>

<head><style>#main{		width:auto;	height:auto;	margin:10%;	text-align:center;	padding:30px;	margin-top:70px;	border-radius:30px;	box-shadow: 0px 0px 2px 3px #000;	background:white;    background: rgba(0, 0, 0, 0.5);	}#main:hover{			box-shadow:0px 2px 5px 3px white;}body{ padding: 0px;  background-image: url("ministry_banner.jpg");  background-repeat: no-repeat;  background-attachment: fixed;  background-size: cover;   background-position: center;}.topnav {  overflow: hidden;  border-bottom:solid black;  }.heading		{			font-size:18;			color:red;			border-bottom:solid black;			width:100%;			text-align:left;"		}.button {  background: none;  border: 3px solid white;  width:120px;  border-radius: 15px;  color: white;  text-align: center;  text-decoration: none;  display: inline-block;  font-size: 16px;  margin: 9px 5px;  padding: 10px 10px;  cursor: pointer;  transition-duration: 0.4s;}.button:hover {  background-color: #008CBA;  color: white;}#btn{	width:100px;	height:25px;	background-color:33F3FF;	box-shadow:0px 0px 2px 1px grey;	border-radius:10px;	transition: 1s;	font-family:Copperplate;	font-weight:bold;	font-size:15;	}#btn:hover{		transform: scale(1.1);				z-index: 2;		box-shadow: 2px 2px 2px #000;		}.content{	background:none;	width:auto;	border:none;	float:left;	font-size:12;		color: #f1f1f1;}.footer {  padding: 20px;  text-align: center;  background: black;  margin-top: 20px;  color:white;background: rgba(0, 0, 0, 0.5);	}  </style>
<title>New Complaint:<?php echo $b['user'];?></title>
</head>


<body><div class="topnav">		<img src="logo.png" alt="Girl in a jacket" width="289" height="60">				<a class="button" href="home.php" style="float:right">Home</a></div><div id="main">
<a style="font-size:15;color:white;float:center"><?phpecho "Date & TIme: " . date("Y-m-d") ."&nbsp&nbsp". date("h:i:sa");?></a>
<h2 style="text-shadow: 2px 2px 5px white;widht:100%;background:#008CBA;border-radius:10px;" >Online Register Your Complaint<br>Samadhan</h2><br><form style="width:100%;height:auto;" action="" method="GET">			<h4 class="heading">Applicant Details</h4>							<p>								<input class="content" placeholder="User Name"  	name="user"	value="">							<input class="content" type="text" 		placeholder="DD-MM-YYYY"  	name="DOB"	value="">							<input class="content"type="text" 		placeholder="Mobile No."  	name="Mobile" value="">							<input class="content"type="email" 		placeholder="Email"  	name="Email" value="<?php echo $b['email'];?>" disabled>							<input class="content"type="text" 		placeholder="Adhaar Card No."  	name="adhaar" value=""><br>							<input  class="content" style="width:100%;"type="text" 	placeholder="Enter Your Address" 	 	name="address">								</p><br>			<h4 class="heading">Complaint Details</h4><br>							<p style="float:left;color:white;"> Subject:-</p>							<textarea style="width:100%;border-bottom:solid black;" class="content" name="subject" rows="1" cols="125" placeholder="Type Subject(Max. 100 Words)"></textarea><br><br>							<p style="float:left;color:white;"> Application Details:-</p><br>							<textarea style="width:100%;height:30%;" class="content" name="statement" rows="20" cols="125" placeholder="Type in Details(Max. 1000 Words)..."></textarea>							<br><br>
			<h4 class="heading">Reference Document and Details of Your Complaint</h4>							<input style="width:100%;" type="file" name="img" style="color:white;float:left;display: inline-block;font-size:13px;"><br>							<p style="color:red;">I declare that all the details and information provided by me are correct & completed.</p><br>
							<input style="width:90%;margin-top:4%;" class="button" type="submit" name="submit" value="Submit a Complaint"><br>
</form><?phpif($_GET['submit']){
$email=	$b['email'];$user=$_GET['user'];$mobile=$_GET['Mobile'];$DOB=$_GET['DOB'];$address=$_GET['address'];$subject=$_GET['subject'];$statement=$_GET['statement'];$cn=$mobile.date("his");$time="Date: ".date("Y-m-d")." TIme: ".date("h:i:sa");$status="pending";$date=date("d-m-y");}if($email!="" && $user!="" && $mobile!="" && $DOB!="" && $address!="" && $subject!="" && $statement!=""){echo"Succ";
$query="INSERT INTO complaint VALUES('$email','$cn','$user','$mobile','$DOB','$address','$subject','$statement','$time','$status')";$result=mysqli_query($conn,$query);if($result){	$query="INSERT INTO new_complaint VALUES('$cn','$date','$status')";	$result=mysqli_query($conn,$query);	$_SESSION['heading']="Complaint Number";	$_SESSION['cn']=$cn;	header('location:cn.php');}else{	echo"Something Went Wrong..";}}
?>
</div><div class="footer">  <h5>© Content owned, updated by the Online Consumer Complaint's Portal. Website is designed, developed, maintained and hosted by <br>Avantika Mishra.</h5></div>
</body>
</html>





