<?php include("connection.php");error_reporting(0);SESSION_start();if($agent_id =""){	header('location:180.47.140.25.php');}?>
<html>

<head><style>#main{		width:auto;	height:auto;	margin:10%;	text-align:center;	padding:30px;	margin-top:70px;	border-radius:30px;	box-shadow: 0px 0px 2px 3px #000;	background:grey;   }#main:hover{			box-shadow:0px 2px 5px 3px white;}body{ padding: 0px;  background-image: url("admin_background.jpg");  background-repeat: no-repeat;  background-attachment: fixed;  background-size: cover;   background-position: center;}.topnav {  overflow: hidden;  border-bottom:solid black;  }.heading		{			font-size:18;			color:red;			border-bottom:solid black;			width:100%;			text-align:left;"		}.button {  background: none;  border: 3px solid white;  width:120px;  border-radius: 15px;  color: white;  text-align: center;  text-decoration: none;  display: inline-block;  font-size: 16px;  margin: 9px 5px;  padding: 10px 10px;  cursor: pointer;  transition-duration: 0.4s;}.button:hover {  background-color: #008CBA;  color: white;}#btn{	width:100px;	height:25px;	background-color:33F3FF;	box-shadow:0px 0px 2px 1px grey;	border-radius:10px;	transition: 1s;	font-family:Copperplate;	font-weight:bold;	font-size:15;	}table{width:100%;}table,th,td{		height:auto;	text-align: center;	padding-right:2%;	border-collapse:collapse;	border:2px solid black;	color:black;	margin:auto;	font-size:18px;	}td{		color:white;	font-size:12px;}.content{	background:none;	width:auto;	border:none;	float:left;	font-size:12;		color: #f1f1f1;}.footer {  padding: 20px;  text-align: center;  background: black;  margin-top: 20px;  color:white;background: rgba(0, 0, 0, 0.5);	}  </style>
<title>New Complaint:<?php echo $b['user'];?></title>
</head>


<body><div class="topnav">		<img src="logo.png" alt="Girl in a jacket" width="289" height="60">				<a class="button" href="workplace.php" style="float:right">Home</a></div><div id="main">
<a style="font-size:15;color:white;float:right"><?phpecho "Date & TIme: " . date("d-m-y") ."&nbsp&nbsp". date("h:i:sa");?></a>			<form id="btn" style="width:auto;float:left;" action="" method="GET">						<input id="btn" style="width:auto;float:left;"class="content"type="text"placeholder="Enter Complaint Number"  	name="cn">						<input style="width:auto;float:right;" id="btn" type="submit" name="submit" value="View Data">					</form><br>					<br>
<h2 style="text-shadow: 2px 2px 5px white;widht:100%;background:green;border-radius:10px;" >Complaint's Management System</h2><br><?phpif(isset($_GET['submit'])){	$casenumber=$_GET['cn'];$_SESSION['cn']=$cn;$cn=$_GET['cn'];$query="SELECT * FROM complaint WHERE cn='$cn'";$result=mysqli_query($conn,$query);$b=mysqli_fetch_assoc($result);}?>			<h4 class="heading">Applicant Details  <p style="float:right;"></h4>														<table> 								<tr>	<th>User Name</th>										<th>Mobile</th>										<th>DOB</th>								</tr><br/>																								<?php																						echo "<tr>															<td>".$b['user']."</td>															<td>".$b['mobile']."</td>															<td>".$b['DOB']."</td>														  </tr><br/>";								?>										<tr>												<th>Email</th>										<th>Addhaar</th>										<th>Address</th>										</tr>														<?php  														echo  "<tr>															<td>".$b['email']."</td>															<td>".$b['adhaar']."</td>															<td>".$b['address']."</td>																 </tr> <br/>";																				?>																												</table>			<h4 class="heading">Complaint Details</h4><br>							<p style="float:left;color:white;"> Subject:-</p>							<input style="width:100%;border-bottom:solid black;" class="content" name="subject" value="<?php echo $b['subject'];?>" disabled " placeholder="Type Subject(Max. 100 Words)"></input><br><br>							<p style= "float:left; color:white; width:100%;text-align:left;"> Application Details:-</p><br>							<p style="width:100%;height:auto;color:white" ><?php echo $b['statement'];?>"</p>							<br><br><br>
			<h4 class="heading">Update Complaint Status</h4>			<form style="width:100%;height:auto;" action="" method="GET">							<input  type="text" name="cn" value="<?php echo $b['cn'];?>" style= "background:none;float:left; color:white; width:auto;"  ><br>							<br><input id="btn" type="text" name="status" style= "float:left; color:white; width:auto;text-align:left;"placeholder="Update Status" ><br>							<p style="color:red;">I declare that all the details and information provided by me are correct & completed.</p><br>
							<input style="width:90%;margin-top:4%;" class="button" type="submit" name="submit" value="Submit a Complaint"><br>
</form><?phpif($_GET['submit']){$status=$_GET['status'];$cn=$_GET['cn'];}if($status!="" && $cn!=""){
$query1="UPDATE complaint set status='$status' WHERE cn='$cn'";$query2="UPDATE new_complaint set status='$status' WHERE cn='$cn'";$result1=mysqli_query($conn,$query1);$result2=mysqli_query($conn,$query2);if($result1){	if($result2)	{		echo "Successfully FIled";			}	else{	echo"Something Went Wrong..";}}}
?>
</div><div class="footer">  <h5>© Content owned, updated by the Online Consumer Complaint's Portal. Website is designed, developed, maintained and hosted by <br>Avantika Mishra.</h5></div>
</body>
</html>





